name: Process Museum Events

on:
  schedule:
    # Run every Monday at 9 AM EST (2 PM UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil
          
      - name: Process CSV files
        run: |
          cd scraper
          # Create the csv_to_events.py file if it doesn't exist
          if [ -f "csv_to_events.py" ]; then
            echo "1" | python csv_to_events.py
          else
            echo "csv_to_events.py not found, using scraper.py"
            mkdir -p ../data
            python scraper.py
          fi
          
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/events.json
          git diff --staged --quiet || git commit -m "Update events from CSV files"
          git push
